# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/upgraded-parakeet

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-node-cache-{{ checksum "package.json" }}

      - restore_cache:
          keys:
          - v1-bower-cache-{{ checksum "bower.json" }}


      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-node-cache-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - bower_components
          key: v1-bower-cache-{{ checksum "bower.json" }}

      - run: npm run build
